# Generated by Django 2.2.12 on 2020-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200509_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
