# Generated by Django 2.2.12 on 2020-05-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200510_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='seen',
        ),
    ]
