# Generated by Django 2.2.12 on 2020-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_image',
            field=models.FileField(default=2, upload_to='meme_photos'),
            preserve_default=False,
        ),
    ]
