# Generated by Django 2.2.12 on 2020-04-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_display_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='display_image',
            new_name='image',
        ),
    ]
