# Generated by Django 2.2.12 on 2020-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200419_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='default_image.jpg', upload_to='meme_photos'),
        ),
    ]
