# Generated by Django 2.2.12 on 2020-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200419_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=2, max_length=280),
            preserve_default=False,
        ),
    ]
